"""init core tables

Revision ID: 06c42658abfe
Revises: 
Create Date: 2025-10-29 22:47:52.958343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06c42658abfe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_dim',
    sa.Column('location_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_table('product_dim',
    sa.Column('product_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('inventory_snapshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('on_hand', sa.Float(), nullable=False),
    sa.Column('on_order', sa.Float(), nullable=False),
    sa.Column('backorder', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location_dim.location_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product_dim.product_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_snapshot_location_id'), 'inventory_snapshot', ['location_id'], unique=False)
    op.create_index(op.f('ix_inventory_snapshot_product_id'), 'inventory_snapshot', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_snapshot_ts'), 'inventory_snapshot', ['ts'], unique=False)
    op.create_table('sales_fact',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_key', sa.Date(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('units', sa.Float(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location_dim.location_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product_dim.product_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_fact_date_key'), 'sales_fact', ['date_key'], unique=False)
    op.create_index(op.f('ix_sales_fact_location_id'), 'sales_fact', ['location_id'], unique=False)
    op.create_index(op.f('ix_sales_fact_product_id'), 'sales_fact', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_fact_product_id'), table_name='sales_fact')
    op.drop_index(op.f('ix_sales_fact_location_id'), table_name='sales_fact')
    op.drop_index(op.f('ix_sales_fact_date_key'), table_name='sales_fact')
    op.drop_table('sales_fact')
    op.drop_index(op.f('ix_inventory_snapshot_ts'), table_name='inventory_snapshot')
    op.drop_index(op.f('ix_inventory_snapshot_product_id'), table_name='inventory_snapshot')
    op.drop_index(op.f('ix_inventory_snapshot_location_id'), table_name='inventory_snapshot')
    op.drop_table('inventory_snapshot')
    op.drop_table('product_dim')
    op.drop_table('location_dim')
    # ### end Alembic commands ###
